// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmmfjijvuyiecaxvbbcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtbWZqaWp2dXlpZWNheHZiYmN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTUyNDMsImV4cCI6MjA3MDQ5MTI0M30.XF3QHT1xXxbf7cWy6x0u2bPh1ptwwUNFm0xLPNQHdQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Define car condition type
export type CarCondition = "new" | "like_new" | "excellent" | "good" | "fair" | "poor";

// Helper function to validate car condition
export const isValidCarCondition = (condition: any): condition is CarCondition => {
  return ["new", "like_new", "excellent", "good", "fair", "poor"].includes(condition);
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});